# Generated by Django 3.0.4 on 2020-03-24 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('title', models.CharField(max_length=100, verbose_name='Название поста')),
                ('text', models.TextField(verbose_name='Содержание поста')),
                ('datetime', models.DateTimeField(verbose_name='Дата публикации')),
                ('thumbnumber', models.IntegerField(default=0, verbose_name='Число лайков')),
                ('viewcount', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('likedone', models.ManyToManyField(related_name='users_post_like', to=settings.AUTH_USER_MODEL)),
                ('viewdone', models.ManyToManyField(related_name='users_post_view', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('text', models.TextField(verbose_name='Содержание комментария')),
                ('datetime', models.DateTimeField(verbose_name='Дата публикации')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Post')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
