# Generated by Django 3.0.4 on 2020-03-26 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0003_auto_20200326_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likedone',
            field=models.ManyToManyField(blank=True, related_name='users_post_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnumber',
            field=models.IntegerField(blank=True, default=0, verbose_name='Число лайков'),
        ),
    ]
