# Generated by Django 3.0.4 on 2020-03-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20200326_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='changed',
            field=models.BooleanField(default=False, verbose_name='Изменена'),
        ),
        migrations.AddField(
            model_name='post',
            name='changed_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения'),
        ),
    ]
